### ISSUE TITLE
update UML diagram

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/representation-task-force#68]
https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#data-interfaces

* [x] Triple alias of Quad #58 
* [x] NamedNode instead of IRI (also factory) #64 
* [x] .literal() constructor #61 
* [x] .blankNode() constructor #60 

possible depending on resolutions of PRs
* [ ] values of .termType #65 
* [ ] factory parameter names #66 

I list above misses something, please just edit it!
